//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceProject.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerData
    {
        public CustomerData()
        {
            this.Addresses = new HashSet<Address>();
            this.PaymentInfoes = new HashSet<PaymentInfo>();
            this.OrderHistories = new HashSet<OrderHistory>();
        }
    
        public int c_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<PaymentInfo> PaymentInfoes { get; set; }
        public virtual ICollection<OrderHistory> OrderHistories { get; set; }
    }
}
