//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public int order_number { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
    
        public virtual CustomerData CustomerData { get; set; }
        public virtual ProductData ProductData { get; set; }
    }
}
