//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductData
    {
        public ProductData()
        {
            this.OrderHistories = new HashSet<OrderHistory>();
        }
    
        public int p_id { get; set; }
        public string product_name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public string tag1 { get; set; }
        public string tag2 { get; set; }
        public string tag3 { get; set; }
        public Nullable<int> stock { get; set; }
        public string imageurl { get; set; }
    
        public virtual ICollection<OrderHistory> OrderHistories { get; set; }
    }
}
