//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceProject.Website.WebsiteServerHost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebsiteServerHost.IDataRetrieverService")]
    public interface IDataRetrieverService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRetrieverService/ReadData", ReplyAction="http://tempuri.org/IDataRetrieverService/ReadDataResponse")]
        System.Collections.Generic.List<EcommerceProject.DatabaseModel.ProductData> ReadData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRetrieverService/ReadData", ReplyAction="http://tempuri.org/IDataRetrieverService/ReadDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EcommerceProject.DatabaseModel.ProductData>> ReadDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRetrieverService/SearchData", ReplyAction="http://tempuri.org/IDataRetrieverService/SearchDataResponse")]
        System.Collections.Generic.List<EcommerceProject.DatabaseModel.ProductData> SearchData(string searchFor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataRetrieverService/SearchData", ReplyAction="http://tempuri.org/IDataRetrieverService/SearchDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EcommerceProject.DatabaseModel.ProductData>> SearchDataAsync(string searchFor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataRetrieverServiceChannel : EcommerceProject.Website.WebsiteServerHost.IDataRetrieverService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataRetrieverServiceClient : System.ServiceModel.ClientBase<EcommerceProject.Website.WebsiteServerHost.IDataRetrieverService>, EcommerceProject.Website.WebsiteServerHost.IDataRetrieverService {
        
        public DataRetrieverServiceClient() {
        }
        
        public DataRetrieverServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataRetrieverServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataRetrieverServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataRetrieverServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<EcommerceProject.DatabaseModel.ProductData> ReadData() {
            return base.Channel.ReadData();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EcommerceProject.DatabaseModel.ProductData>> ReadDataAsync() {
            return base.Channel.ReadDataAsync();
        }
        
        public System.Collections.Generic.List<EcommerceProject.DatabaseModel.ProductData> SearchData(string searchFor) {
            return base.Channel.SearchData(searchFor);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EcommerceProject.DatabaseModel.ProductData>> SearchDataAsync(string searchFor) {
            return base.Channel.SearchDataAsync(searchFor);
        }
    }
}
